### ISSUE TITLE
按照格式添加友链后出现奇奇怪怪的字符

### ISSUE THREAD

**Issue by AndreaOm** [Dalodd/Mirages-For-Typecho#1]
![QAQ](http://ww4.sinaimg.cn/large/a15b4afegw1f5ifyxp4umj20x60hc0t5)
# QAQ

**Comment by Dalodd** [comment]
可以把编辑器里的内容贴出来看一下嘛

**Comment by AndreaOm** [comment]
### 菊苣们
[Typecho](http://typecho.org)+(http://image.qiniudn.com/head.png?imageView2/2/w/400/q/50)
[哈哈](http://haha.cn)+(http://image.qiniudn.com/head.png)
[haha](https://haha.en)+(http://image.qiniudn.com/head.png)
### 逗比
[Hran](https://hran.me)+(http://duanjstatic.qiniudn.com/hran/2016/01/07/145213578473155_labtocat.png?imageView2/2/w/400/q/85)
嗯。。。

就是用的这个

**Comment by Dalodd** [comment]
奇怪了，你看一下是不是多输入什么了
