### ISSUE TITLE
请问一下如何不显示全文，而是概述

### ISSUE THREAD

**Issue by ccw1996** [Dalodd/Mirages-For-Typecho#10]
您好，请问一下如何不显示全文，我看到您的php文件里面貌似有这个功能，但我并不会php，无法很好的修改它，希望您能告诉我一下如何实现这个功能，谢谢

**Comment by smartpippin** [comment]
哈，这个，我这个小白可以回答你。。这根主题木有关系。。在后台[设置]-[阅读]里面有，选择[仅输出摘要]就好。记得文章中用分隔符。O(∩_∩)O

**Comment by ccw1996** [comment]
@smartpippin 非常感谢，原来要用分隔符。十分感谢。

同时谢谢作者的主题，真的兼容美观和简单，大写的赞
