### ISSUE TITLE
自定义字段添加 banner 后依旧无效 Nothing changed after adding custom fields - ‘banner’

### ISSUE THREAD

**Issue by AirScr** [Dalodd/Mirages-For-Typecho#3]
按照 wiki 添加 banner 后无效
Nothing has changed even follow the instruction of wiki.

**Comment by Dalodd** [comment]
PHP 版本？

**Comment by AirScr** [comment]
php7

**Comment by Dalodd** [comment]
这个可能会有些问题。稍后回复你

**Comment by Dalodd** [comment]
我本地测试没有问题了

**Comment by AirScr** [comment]
![](http://ww2.sinaimg.cn/large/a09f7e2agw1f608niik3qj20pz07emy7.jpg)

难道是我的配置出错了吗？

**Comment by Dalodd** [comment]
配置没有问题。。

**Comment by AirScr** [comment]
这个问题是与PJAX 有关吗

**Comment by Dalodd** [comment]
应该是没有关系的，问题应该出在function.php里的loadArchiveBanner方法，你可以试试在返回空字符串的return语句做些更改，返回不同的假的url，确定一下是在哪个if分支出的问题

**Comment by AirScr** [comment]
已修复。谢谢。问题出在 loadArchiveBanner 方法
Resolved, thanks. The problem lies on the use of loadArchiveBanner.

**Comment by Dalodd** [comment]
如果可以的话，能不能提供一下您的解决方案，或者说明一下具体是什么原因导致的问题，谢谢~

**Comment by AirScr** [comment]
正如您所说，替换所有相关联的 `isset` 字段为 `hasValue`。
As you said above, replace all `isset` into `hasValue` which has been involved.
