### ISSUE TITLE
二维码引用了非SSL内容

### ISSUE THREAD

**Issue by Zhangzijing** [Dalodd/Mirages-For-Typecho#4]
Chrome浏览器提示: Mixed Content: The page at '网页链接' was loaded over HTTPS, but requested an insecure image 'http://b.bshare.cn/barCode?site=weixin&url=网页链接'. This content should also be served over HTTPS.
同时左上角的绿锁标识也消失了

**Comment by Dalodd** [comment]
默认使用了 bshare 的二维码生成服务，这个是不支持 HTTPS 的，这个默认的二维码更多的是演示该如何填写二维码设置。要支持 HTTPS，你可以换用支持 HTTPS 的服务，或使用自己实现的支持 HTTPS 的二维码生成连接。

**Comment by Zhangzijing** [comment]
刚刚找到一个百度网盘的, 感觉比较稳定
https://pan.baidu.com/share/qrcode?w=150&h=150&url=XXX

**Comment by Dalodd** [comment]
可以的，这个不错~
